### PR TITLE
Implement registration form

### PR DESCRIPTION
**Pull request by dheidemann**
google forms api sucks, implemented registration form functionality myself now.

Each umbrella event can have a registration form now.
I seed a default form for a umbrella event with id 1.
Therefore the registration form can be found at http://localhost:8080/registration?e=1

For the reviewer: you dont need to check the backend stuff, just fronted please. Basically the only relevant file is `frontend/app/registration/page.tsx`

### CODE REVIEW

**Comment by Plebysnacc** [comment]
image

There are question which may have no selected answer as "correct" way, maybe implement disabling the validation for those

**Review by Plebysnacc — CHANGES_REQUESTED** [review]
Validation Check is not always needed, makes the form invalid although valid answers may have been given

**Comment by dheidemann** [comment]
This is something i cannot represent in the datastructure. You would have to add another answer with 'Kenne ich alles' for example

**Comment by dheidemann** [comment]
Well you could add this 0 point answer and if it exists i skip the form validation and dont show the answer. A bit sketchy tho

**Comment by dheidemann** [comment]
Nevermind, i have a better idea, gimme 5 min

**Comment by Plebysnacc** [comment]
Is not having a notification for completed submission intended?

**Comment by dheidemann** [comment]
the submission flow is not part of this pr. This needs another table in the database and is going to be implemented afterwards

**Review by Plebysnacc — APPROVED** [review]
lgtm

**Pull request merged**
