### PR TITLE
Add spacing to header elements

### PR DESCRIPTION
**Pull request by Plebysnacc**
This branch adds responsive spacing to the header elements, especially the links.

Things to consider:
- There are some weird pixel-widths that make the "homepage" link disappear, I have not yet found a fix for that. Maybe we wanna push that fix to the implementation of the mobile view, as it seems to only bother very small width windows
- Ignore the commit messages, I fucked up a merge

### CODE REVIEW

**Review by Xeldlie — APPROVED** [review]
Looks good

**Review by dheidemann — APPROVED** [review]
pascht

**Comment by dheidemann** [comment]
walum ita build failing?

**Comment by dheidemann** [comment]
doesnt seem to be related to this pr... continuing in #43

**Pull request merged**
